In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
data = pd.read_csv("heart_attack_prediction_dataset.csv")

In [3]:
data

,Patient ID,Age,Sex,Cholesterol,Blood Pressure,Heart Rate,Diabetes,Family History,Smoking,Obesity,...,Sedentary Hours Per Day,Income,BMI,Triglycerides,Physical Activity Days Per Week,Sleep Hours Per Day,Country,Continent,Hemisphere,Heart Attack Risk
0,BMW7812,67,Male,208,158/88,72,0,0,1,0,...,6.615001,261404,31.251233,286,0,6,Argentina,South America,Southern Hemisphere,0
1,CZE1114,21,Male,389,165/93,98,1,1,1,1,...,4.963459,285768,27.194973,235,1,7,Canada,North America,Northern Hemisphere,0
2,BNI9906,21,Female,324,174/99,72,1,0,0,0,...,9.463426,235282,28.176571,587,4,4,France,Europe,Northern Hemisphere,0
3,JLN3497,84,Male,383,163/100,73,1,1,1,0,...,7.648981,125640,36.464704,378,3,4,Canada,North America,Northern Hemisphere,0
4,GFO8847,66,Male,318,91/88,93,1,1,1,1,...,1.514821,160555,21.809144,231,1,5,Thailand,Asia,Northern Hemisphere,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8758,MSV9918,60,Male,121,94/76,61,1,1,1,0,...,10.806373,235420,19.655895,67,7,7,Thailand,Asia,Northern Hemisphere,0
8759,QSV6764,28,Female,120,157/102,73,1,0,0,1,...,3.833038,217881,23.993866,617,4,9,Canada,North America,Northern Hemisphere,0
8760,XKA5925,47,Male,250,161/75,105,0,1,1,1,...,2.375214,36998,35.406146,527,4,4,Brazil,South America,Southern Hemisphere,1
8761,EPE6801,36,Male,178,119/67,60,1,0,1,0,...,0.029104,209943,27.294020,114,2,8,Brazil,South America,Southern Hemisphere,0
8762,ZWN9666,25,Female,356,138/67,75,1,1,0,0,...,9.005234,247338,32.914151,180,7,4,United Kingdom,Europe,Northern Hemisphere,1

In [4]:
data.isnull().sum()

Patient ID                         0
Age                                0
Sex                                0
Cholesterol                        0
Blood Pressure                     0
Heart Rate                         0
Diabetes                           0
Family History                     0
Smoking                            0
Obesity                            0
Alcohol Consumption                0
Exercise Hours Per Week            0
Diet                               0
Previous Heart Problems            0
Medication Use                     0
Stress Level                       0
Sedentary Hours Per Day            0
Income                             0
BMI                                0
Triglycerides                      0
Physical Activity Days Per Week    0
Sleep Hours Per Day                0
Country                            0
Continent                          0
Hemisphere                         0
Heart Attack Risk                  0
dtype: int64

In [5]:
data.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
8758    False
8759    False
8760    False
8761    False
8762    False
Length: 8763, dtype: bool

In [6]:
data.dtypes

Patient ID                          object
Age                                  int64
Sex                                 object
Cholesterol                          int64
Blood Pressure                      object
Heart Rate                           int64
Diabetes                             int64
Family History                       int64
Smoking                              int64
Obesity                              int64
Alcohol Consumption                  int64
Exercise Hours Per Week            float64
Diet                                object
Previous Heart Problems              int64
Medication Use                       int64
Stress Level                         int64
Sedentary Hours Per Day            float64
Income                               int64
BMI                                float64
Triglycerides                        int64
Physical Activity Days Per Week      int64
Sleep Hours Per Day                  int64
Country                             object
Continent                           object
Hemisphere                          object
Heart Attack Risk                    int64
dtype: object

In [7]:
data.drop('Patient ID', axis = 1 , inplace = True)

In [8]:
colToDrop = ['Country','Continent','Income','Hemisphere']
data.drop(colToDrop, axis = 1 , inplace = True)

In [9]:
data.head()

,Age,Sex,Cholesterol,Blood Pressure,Heart Rate,Diabetes,Family History,Smoking,Obesity,Alcohol Consumption,...,Diet,Previous Heart Problems,Medication Use,Stress Level,Sedentary Hours Per Day,BMI,Triglycerides,Physical Activity Days Per Week,Sleep Hours Per Day,Heart Attack Risk
0,67,Male,208,158/88,72,0,0,1,0,0,...,Average,0,0,9,6.615001,31.251233,286,0,6,0
1,21,Male,389,165/93,98,1,1,1,1,1,...,Unhealthy,1,0,1,4.963459,27.194973,235,1,7,0
2,21,Female,324,174/99,72,1,0,0,0,0,...,Healthy,1,1,9,9.463426,28.176571,587,4,4,0
3,84,Male,383,163/100,73,1,1,1,0,1,...,Average,1,0,9,7.648981,36.464704,378,3,4,0
4,66,Male,318,91/88,93,1,1,1,1,0,...,Unhealthy,1,0,6,1.514821,21.809144,231,1,5,0

In [10]:
data.dtypes

Age                                  int64
Sex                                 object
Cholesterol                          int64
Blood Pressure                      object
Heart Rate                           int64
Diabetes                             int64
Family History                       int64
Smoking                              int64
Obesity                              int64
Alcohol Consumption                  int64
Exercise Hours Per Week            float64
Diet                                object
Previous Heart Problems              int64
Medication Use                       int64
Stress Level                         int64
Sedentary Hours Per Day            float64
BMI                                float64
Triglycerides                        int64
Physical Activity Days Per Week      int64
Sleep Hours Per Day                  int64
Heart Attack Risk                    int64
dtype: object

In [11]:
data['Sex'].unique()

array(['Male', 'Female'], dtype=object)

In [12]:
data.replace({'Male':1 , "Female" :0}, inplace=True)

In [13]:
data

,Age,Sex,Cholesterol,Blood Pressure,Heart Rate,Diabetes,Family History,Smoking,Obesity,Alcohol Consumption,...,Diet,Previous Heart Problems,Medication Use,Stress Level,Sedentary Hours Per Day,BMI,Triglycerides,Physical Activity Days Per Week,Sleep Hours Per Day,Heart Attack Risk
0,67,1,208,158/88,72,0,0,1,0,0,...,Average,0,0,9,6.615001,31.251233,286,0,6,0
1,21,1,389,165/93,98,1,1,1,1,1,...,Unhealthy,1,0,1,4.963459,27.194973,235,1,7,0
2,21,0,324,174/99,72,1,0,0,0,0,...,Healthy,1,1,9,9.463426,28.176571,587,4,4,0
3,84,1,383,163/100,73,1,1,1,0,1,...,Average,1,0,9,7.648981,36.464704,378,3,4,0
4,66,1,318,91/88,93,1,1,1,1,0,...,Unhealthy,1,0,6,1.514821,21.809144,231,1,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8758,60,1,121,94/76,61,1,1,1,0,1,...,Healthy,1,1,8,10.806373,19.655895,67,7,7,0
8759,28,0,120,157/102,73,1,0,0,1,0,...,Healthy,0,0,8,3.833038,23.993866,617,4,9,0
8760,47,1,250,161/75,105,0,1,1,1,1,...,Average,1,0,5,2.375214,35.406146,527,4,4,1
8761,36,1,178,119/67,60,1,0,1,0,0,...,Unhealthy,1,1,5,0.029104,27.294020,114,2,8,0
8762,25,0,356,138/67,75,1,1,0,0,1,...,Healthy,0,0,8,9.005234,32.914151,180,7,4,1

In [14]:
# pd.get_dummies(data)
diets = data['Diet'].unique()

In [15]:
diets

array(['Average', 'Unhealthy', 'Healthy'], dtype=object)

In [16]:
data["Diet"].replace({"Average":0, "Healthy":1 , "Unhealthy":2} , inplace = True)
# data["Diet"].replace({diets[0]:0, diets[1]:1 , diets[2]:2}, inplace = True)
# data["Diet"]

In [17]:
data

,Age,Sex,Cholesterol,Blood Pressure,Heart Rate,Diabetes,Family History,Smoking,Obesity,Alcohol Consumption,...,Diet,Previous Heart Problems,Medication Use,Stress Level,Sedentary Hours Per Day,BMI,Triglycerides,Physical Activity Days Per Week,Sleep Hours Per Day,Heart Attack Risk
0,67,1,208,158/88,72,0,0,1,0,0,...,0,0,0,9,6.615001,31.251233,286,0,6,0
1,21,1,389,165/93,98,1,1,1,1,1,...,2,1,0,1,4.963459,27.194973,235,1,7,0
2,21,0,324,174/99,72,1,0,0,0,0,...,1,1,1,9,9.463426,28.176571,587,4,4,0
3,84,1,383,163/100,73,1,1,1,0,1,...,0,1,0,9,7.648981,36.464704,378,3,4,0
4,66,1,318,91/88,93,1,1,1,1,0,...,2,1,0,6,1.514821,21.809144,231,1,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8758,60,1,121,94/76,61,1,1,1,0,1,...,1,1,1,8,10.806373,19.655895,67,7,7,0
8759,28,0,120,157/102,73,1,0,0,1,0,...,1,0,0,8,3.833038,23.993866,617,4,9,0
8760,47,1,250,161/75,105,0,1,1,1,1,...,0,1,0,5,2.375214,35.406146,527,4,4,1
8761,36,1,178,119/67,60,1,0,1,0,0,...,2,1,1,5,0.029104,27.294020,114,2,8,0
8762,25,0,356,138/67,75,1,1,0,0,1,...,1,0,0,8,9.005234,32.914151,180,7,4,1

In [18]:
data[['Systolic ','Diasystolic']] = data["Blood Pressure"].str.split("/",expand = True)

In [19]:
data

,Age,Sex,Cholesterol,Blood Pressure,Heart Rate,Diabetes,Family History,Smoking,Obesity,Alcohol Consumption,...,Medication Use,Stress Level,Sedentary Hours Per Day,BMI,Triglycerides,Physical Activity Days Per Week,Sleep Hours Per Day,Heart Attack Risk,Systolic,Diasystolic
0,67,1,208,158/88,72,0,0,1,0,0,...,0,9,6.615001,31.251233,286,0,6,0,158,88
1,21,1,389,165/93,98,1,1,1,1,1,...,0,1,4.963459,27.194973,235,1,7,0,165,93
2,21,0,324,174/99,72,1,0,0,0,0,...,1,9,9.463426,28.176571,587,4,4,0,174,99
3,84,1,383,163/100,73,1,1,1,0,1,...,0,9,7.648981,36.464704,378,3,4,0,163,100
4,66,1,318,91/88,93,1,1,1,1,0,...,0,6,1.514821,21.809144,231,1,5,0,91,88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8758,60,1,121,94/76,61,1,1,1,0,1,...,1,8,10.806373,19.655895,67,7,7,0,94,76
8759,28,0,120,157/102,73,1,0,0,1,0,...,0,8,3.833038,23.993866,617,4,9,0,157,102
8760,47,1,250,161/75,105,0,1,1,1,1,...,0,5,2.375214,35.406146,527,4,4,1,161,75
8761,36,1,178,119/67,60,1,0,1,0,0,...,1,5,0.029104,27.294020,114,2,8,0,119,67
8762,25,0,356,138/67,75,1,1,0,0,1,...,0,8,9.005234,32.914151,180,7,4,1,138,67

In [20]:
data.dtypes

Age                                  int64
Sex                                  int64
Cholesterol                          int64
Blood Pressure                      object
Heart Rate                           int64
Diabetes                             int64
Family History                       int64
Smoking                              int64
Obesity                              int64
Alcohol Consumption                  int64
Exercise Hours Per Week            float64
Diet                                 int64
Previous Heart Problems              int64
Medication Use                       int64
Stress Level                         int64
Sedentary Hours Per Day            float64
BMI                                float64
Triglycerides                        int64
Physical Activity Days Per Week      int64
Sleep Hours Per Day                  int64
Heart Attack Risk                    int64
Systolic                            object
Diasystolic                         object
dtype: object

In [21]:
data['Systolic '],data['Diasystolic'] = data['Systolic '].astype('int64'), data['Diasystolic'].astype("int64")
data.dtypes

Age                                  int64
Sex                                  int64
Cholesterol                          int64
Blood Pressure                      object
Heart Rate                           int64
Diabetes                             int64
Family History                       int64
Smoking                              int64
Obesity                              int64
Alcohol Consumption                  int64
Exercise Hours Per Week            float64
Diet                                 int64
Previous Heart Problems              int64
Medication Use                       int64
Stress Level                         int64
Sedentary Hours Per Day            float64
BMI                                float64
Triglycerides                        int64
Physical Activity Days Per Week      int64
Sleep Hours Per Day                  int64
Heart Attack Risk                    int64
Systolic                             int64
Diasystolic                          int64
dtype: object

# ###Dropping less important Features

In [22]:
data.drop(["Blood Pressure"], axis = 1 , inplace = True)

In [23]:
data.dtypes

Age                                  int64
Sex                                  int64
Cholesterol                          int64
Heart Rate                           int64
Diabetes                             int64
Family History                       int64
Smoking                              int64
Obesity                              int64
Alcohol Consumption                  int64
Exercise Hours Per Week            float64
Diet                                 int64
Previous Heart Problems              int64
Medication Use                       int64
Stress Level                         int64
Sedentary Hours Per Day            float64
BMI                                float64
Triglycerides                        int64
Physical Activity Days Per Week      int64
Sleep Hours Per Day                  int64
Heart Attack Risk                    int64
Systolic                             int64
Diasystolic                          int64
dtype: object

In [24]:
data

,Age,Sex,Cholesterol,Heart Rate,Diabetes,Family History,Smoking,Obesity,Alcohol Consumption,Exercise Hours Per Week,...,Medication Use,Stress Level,Sedentary Hours Per Day,BMI,Triglycerides,Physical Activity Days Per Week,Sleep Hours Per Day,Heart Attack Risk,Systolic,Diasystolic
0,67,1,208,72,0,0,1,0,0,4.168189,...,0,9,6.615001,31.251233,286,0,6,0,158,88
1,21,1,389,98,1,1,1,1,1,1.813242,...,0,1,4.963459,27.194973,235,1,7,0,165,93
2,21,0,324,72,1,0,0,0,0,2.078353,...,1,9,9.463426,28.176571,587,4,4,0,174,99
3,84,1,383,73,1,1,1,0,1,9.828130,...,0,9,7.648981,36.464704,378,3,4,0,163,100
4,66,1,318,93,1,1,1,1,0,5.804299,...,0,6,1.514821,21.809144,231,1,5,0,91,88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8758,60,1,121,61,1,1,1,0,1,7.917342,...,1,8,10.806373,19.655895,67,7,7,0,94,76
8759,28,0,120,73,1,0,0,1,0,16.558426,...,0,8,3.833038,23.993866,617,4,9,0,157,102
8760,47,1,250,105,0,1,1,1,1,3.148438,...,0,5,2.375214,35.406146,527,4,4,1,161,75
8761,36,1,178,60,1,0,1,0,0,3.789950,...,1,5,0.029104,27.294020,114,2,8,0,119,67
8762,25,0,356,75,1,1,0,0,1,18.081748,...,0,8,9.005234,32.914151,180,7,4,1,138,67

In [25]:
data.columns

Index(['Age', 'Sex', 'Cholesterol', 'Heart Rate', 'Diabetes', 'Family History',
       'Smoking', 'Obesity', 'Alcohol Consumption', 'Exercise Hours Per Week',
       'Diet', 'Previous Heart Problems', 'Medication Use', 'Stress Level',
       'Sedentary Hours Per Day', 'BMI', 'Triglycerides',
       'Physical Activity Days Per Week', 'Sleep Hours Per Day',
       'Heart Attack Risk', 'Systolic ', 'Diasystolic'],
      dtype='object')

In [26]:
for index , col in enumerate(data.columns):
    print(index , col)

0 Age
1 Sex
2 Cholesterol
3 Heart Rate
4 Diabetes
5 Family History
6 Smoking
7 Obesity
8 Alcohol Consumption
9 Exercise Hours Per Week
10 Diet
11 Previous Heart Problems
12 Medication Use
13 Stress Level
14 Sedentary Hours Per Day
15 BMI
16 Triglycerides
17 Physical Activity Days Per Week
18 Sleep Hours Per Day
19 Heart Attack Risk
20 Systolic
21 Diasystolic

In [27]:
target = data.pop("Heart Attack Risk")
target

0       0
1       0
2       0
3       0
4       0
       ..
8758    0
8759    0
8760    1
8761    0
8762    1
Name: Heart Attack Risk, Length: 8763, dtype: int64

In [28]:
data.columns

Index(['Age', 'Sex', 'Cholesterol', 'Heart Rate', 'Diabetes', 'Family History',
       'Smoking', 'Obesity', 'Alcohol Consumption', 'Exercise Hours Per Week',
       'Diet', 'Previous Heart Problems', 'Medication Use', 'Stress Level',
       'Sedentary Hours Per Day', 'BMI', 'Triglycerides',
       'Physical Activity Days Per Week', 'Sleep Hours Per Day', 'Systolic ',
       'Diasystolic'],
      dtype='object')

In [29]:
features = data.copy()

In [30]:
features

,Age,Sex,Cholesterol,Heart Rate,Diabetes,Family History,Smoking,Obesity,Alcohol Consumption,Exercise Hours Per Week,...,Previous Heart Problems,Medication Use,Stress Level,Sedentary Hours Per Day,BMI,Triglycerides,Physical Activity Days Per Week,Sleep Hours Per Day,Systolic,Diasystolic
0,67,1,208,72,0,0,1,0,0,4.168189,...,0,0,9,6.615001,31.251233,286,0,6,158,88
1,21,1,389,98,1,1,1,1,1,1.813242,...,1,0,1,4.963459,27.194973,235,1,7,165,93
2,21,0,324,72,1,0,0,0,0,2.078353,...,1,1,9,9.463426,28.176571,587,4,4,174,99
3,84,1,383,73,1,1,1,0,1,9.828130,...,1,0,9,7.648981,36.464704,378,3,4,163,100
4,66,1,318,93,1,1,1,1,0,5.804299,...,1,0,6,1.514821,21.809144,231,1,5,91,88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8758,60,1,121,61,1,1,1,0,1,7.917342,...,1,1,8,10.806373,19.655895,67,7,7,94,76
8759,28,0,120,73,1,0,0,1,0,16.558426,...,0,0,8,3.833038,23.993866,617,4,9,157,102
8760,47,1,250,105,0,1,1,1,1,3.148438,...,1,0,5,2.375214,35.406146,527,4,4,161,75
8761,36,1,178,60,1,0,1,0,0,3.789950,...,1,1,5,0.029104,27.294020,114,2,8,119,67
8762,25,0,356,75,1,1,0,0,1,18.081748,...,0,0,8,9.005234,32.914151,180,7,4,138,67

# train and test split

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
TrainData , TestData ,TrainTarget, testTarget = train_test_split(features, target , test_size = 0.20, random_state=0)

In [33]:
TrainData = np.array(TrainData)
TestData = np.array(TestData)
TrainTarget = np.array(TrainTarget)
TestTarget = np.array(testTarget)

In [34]:
TrainData.shape , TestData.shape , TrainTarget.shape , testTarget.shape

((7010, 21), (1753, 21), (7010,), (1753,))

# fitting the ML model

In [35]:
from sklearn.linear_model import LogisticRegression

# Logistic Regression

In [36]:
classifier = LogisticRegression()

In [37]:
classifier.fit(TrainData ,TrainTarget)

E:\ProgramData\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [38]:
# TestData[0] , testTarget[0]

In [39]:
testPreds = classifier.predict(TestData)
trainPreds =classifier.predict(TrainData)

In [40]:
testPreds

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [41]:
trainPreds

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [42]:
# classifier.score(testTarget, testPreds)

In [43]:
import numpy as np
from sklearn.metrics import accuracy_score

# # Assuming testPreds are probability scores for binary classification
# threshold = 0.5
# binary_preds = np.where(testPreds >= threshold, 1, 0)

TestAccuracy = round(accuracy_score(testTarget, testPreds)*100,2)
print("Test Accuracy is", TestAccuracy , "%")

Test Accuracy is 63.55 %

In [44]:
# # Assuming testPreds are probability scores for binary classification
# threshold = 0.5
# binary_preds = np.where(trainPreds >= threshold, 1, 0)

TrainAccuracy = round(accuracy_score(TrainTarget, trainPreds)*100,2)
print("Train Accuracy is", TrainAccuracy,"%")

Train Accuracy is 64.34 %

# Decison Tree classifier

In [45]:
#Model training
from sklearn.tree import DecisionTreeClassifier

In [46]:
Dtree = DecisionTreeClassifier()
Dtree.fit(TrainData ,TrainTarget)

DecisionTreeClassifier()

In [47]:
# Evaluation 
from sklearn.metrics import accuracy_score
Pred_test = Dtree.predict(TestData)
print("Decision tree Evaluation")
accuracy = round(accuracy_score(TestTarget , Pred_test)*100,2)
print("accuray is ",accuracy ,"%")

Decision tree Evaluation
accuray is  54.54 %

In [48]:
import pickle 
with open("Dtree", "wb") as new:
    pickle.dump(Dtree , new)

#    Saving the model

In [49]:
import pickle

In [50]:
with open("LogisticRegression.pkl","wb") as m:
    pickle.dump(classifier, m)

In [51]:
# load model
with open("./LogisticRegression.pkl","rb") as m:
    loaded_model = pickle.load(m)

In [52]:
loaded_model

LogisticRegression()

In [53]:
pred = loaded_model.predict(TestData)

In [54]:
pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)